staticVoidCall=try (MockedStatic<%2$s> mocked = Mockito.mockStatic(%2$s.class)) {\n    mocked.when(() -> %2$s.%3$s(%4$s));\n    // TODO: configure side effects for %2$s.%3$s\n}
newObjectInvocation=%1$s %2$s = Mockito.mock(%1$s.class);\nMockito.when(%2$s.%3$s(%4$s)).thenReturn(%5$s);
