package com.example.tests.generator.method;

import java.util.List;
import java.util.Objects;

/**
 * Applies mock snippets generated by {@link MethodMockGenerator} back to the original
 * method source, replacing the logical code units that triggered the rules.
 */
public class MethodMockMerger {

    /**
     * Replaces all occurrences of the original code captured by the provided snippets inside the
     * supplied method source with their mocked variants.
     *
     * @param methodSource original method source (as produced by the analyzer)
     * @param snippets     mock snippets that should replace matching code units
     * @return merged source that contains rendered mocks instead of the original code fragments
     */
    public String merge(String methodSource, List<MockSnippet> snippets) {
        if (methodSource == null || methodSource.isEmpty() || snippets == null || snippets.isEmpty()) {
            return methodSource;
        }
        String merged = methodSource;
        for (MockSnippet snippet : snippets) {
            merged = mergeSnippet(merged, snippet);
        }
        return merged;
    }

    /**
     * Convenience overload that works with a {@link MethodMockPlan} directly.
     */
    public String merge(MethodMockPlan plan) {
        Objects.requireNonNull(plan, "plan");
        return merge(plan.methodSource(), plan.snippets());
    }

    private String mergeSnippet(String methodSource, MockSnippet snippet) {
        if (snippet == null) {
            return methodSource;
        }
        String original = snippet.originalCode();
        String replacement = snippet.mockCode();
        if (original == null || original.isBlank() || replacement == null || replacement.isBlank()) {
            return methodSource;
        }
        String trimmedOriginal = original.trim();
        int matchIndex = findMatch(methodSource, trimmedOriginal);
        if (matchIndex < 0) {
            return methodSource;
        }
        int lineStart = locateLineStart(methodSource, matchIndex);
        int lineEnd = locateLineEnd(methodSource, matchIndex + trimmedOriginal.length());
        String indentation = methodSource.substring(lineStart, matchIndex);
        String indentedReplacement = indentReplacement(replacement, indentation);
        return methodSource.substring(0, lineStart) + indentedReplacement + methodSource.substring(lineEnd);
    }

    private int findMatch(String source, String needle) {
        if (needle.isEmpty()) {
            return -1;
        }
        return source.indexOf(needle);
    }

    private int locateLineStart(String source, int index) {
        int cursor = Math.min(index, source.length());
        while (cursor > 0) {
            char prev = source.charAt(cursor - 1);
            if (prev == '\n' || prev == '\r') {
                break;
            }
            cursor--;
        }
        return cursor;
    }

    private int locateLineEnd(String source, int index) {
        int cursor = Math.max(0, index);
        while (cursor < source.length()) {
            char ch = source.charAt(cursor);
            if (ch == '\n' || ch == '\r') {
                break;
            }
            if (ch == ' ' || ch == '\t') {
                cursor++;
                continue;
            }
            break;
        }
        return cursor;
    }

    private String indentReplacement(String replacement, String indentation) {
        String[] lines = replacement.split("\\R", -1);
        StringBuilder builder = new StringBuilder(replacement.length() + indentation.length() * lines.length);
        for (int i = 0; i < lines.length; i++) {
            if (i > 0) {
                builder.append('\n');
            }
            builder.append(indentation);
            builder.append(lines[i]);
        }
        return builder.toString();
    }
}
